services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_simplified_transactions
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ~/pgdata2:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplified_transactions
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/target
    depends_on:
      - postgres
    command: ["mvn", "spring-boot:run"]

volumes:
  pgdata2:
