spring:
  application:
    name: simplified_transactions

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  flyway:
    baselineOnMigrate: true

server:
  error:
    include-stacktrace: never

mock:
  transaction_authorization:
    url: ${TRANSACTION_AUTHORIZATION_URL}
  send_notification:
    url: ${SEND_NOTIFICATION_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs